// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApz7Jy6EWYrflx9FNgWuCeYo2SRBhJkY',
    appId: '1:941669966890:web:959544248218a483fa4f53',
    messagingSenderId: '941669966890',
    projectId: 'betterbin-80ecf',
    authDomain: 'betterbin-80ecf.firebaseapp.com',
    storageBucket: 'betterbin-80ecf.appspot.com',
    measurementId: 'G-44Z7VYEDMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFju67wJxf5lOoer_pYEF75UlmG843P4I',
    appId: '1:941669966890:android:d215d106dd5b152ffa4f53',
    messagingSenderId: '941669966890',
    projectId: 'betterbin-80ecf',
    storageBucket: 'betterbin-80ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURXpml1wYzYvao1dty2Lds9pB97hhSyQ',
    appId: '1:941669966890:ios:a5a21d7a2d931215fa4f53',
    messagingSenderId: '941669966890',
    projectId: 'betterbin-80ecf',
    storageBucket: 'betterbin-80ecf.appspot.com',
    iosClientId: '941669966890-keha6mkp8l3smf45s1vhfgjd98oo4c1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterbin',
  );
}
